comment: false
ignore:
  - "src/RcppExports.cpp"
  - "src/Polygon_repair.h"
  - "src/Enhanced_constrained_triangulation_2.h"
  - "src/prepr.cpp"

coverage:
  status:
    patch:
      default:
        target: 0
        threshold: 100
    project:
      default:
        target: 70
        threshold: 100
