// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CPL_prepair
Rcpp::List CPL_prepair(Rcpp::List sfc, double min_area, bool point_set);
RcppExport SEXP _prepair_CPL_prepair(SEXP sfcSEXP, SEXP min_areaSEXP, SEXP point_setSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type sfc(sfcSEXP);
    Rcpp::traits::input_parameter< double >::type min_area(min_areaSEXP);
    Rcpp::traits::input_parameter< bool >::type point_set(point_setSEXP);
    rcpp_result_gen = Rcpp::wrap(CPL_prepair(sfc, min_area, point_set));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_prepair_CPL_prepair", (DL_FUNC) &_prepair_CPL_prepair, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_prepair(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
